const SERVER_ROUTES = {
  HOME: "/",
  CATEGORIES: "/categories",
  LOGIN: "/auth/login",
  VERIFY: "/auth/verify",
  REFRESH: "/auth/refresh",
  ME: "/auth/me",
  USER: "/user",
  CART: "/cart",
  STATE: "/state",
  CITY: "/city",
  ADD_ADDRESS_TO_CART: "/cart/addAddress",
  ADDRESS: "/address",
  ADD_TO_CART: "/cart/add",
  REMOVE_FROM_CART: "/cart/remove",
  BOOK: "/book",
  SEARCH: "/search",
  QUICK_SEARCH: "/quickSearch",
  LOGOUT: "/auth/logout",
};

const CLIENT_ROUTES = {
  HOME: "/",
  LOGIN: "/auth/login",
  VERIFY: "/auth/verify",
  USER: "/user",
  USER_DETAILS: "/user/details",
  USER_ORDERS: "/user/orders",
  USER_EDIT: "/user/edit",
  USER_LOGOUT: "/user/logout",
  CART: "/cart",
  Add_ADDRESS: "/add-address",
  CATEGORY: "/category",
  BOOK: "/book",
  SEARCH: "/search",
  PUBLISHERS: "/publishers",
  WRITERS: "/writers",
  FAQ: "/faq",
  RULES: "/rules",
  CONTACT_US: "/contact-us",
  ABOUT_US: "/about-us",
};

export { SERVER_ROUTES, CLIENT_ROUTES };
